Repository ordinaryindustries/ReviewKit, pull requests merged in 2024-10, with the labels that each got.

#20 rename ShapeProgressView
  Sources/ReviewKit/RatingImage.swift
  Sources/ReviewKit/RatingPosition.swift
  Sources/ReviewKit/RatingRow.swift
  Sources/ReviewKit/ReviewKit.swift
Labels: Hacktoberfest-accepted

#25 [SWIFTLINT] - Adding swiftlint to the project
  .swiftlint.yml
  Package.resolved
  Package.swift
  Sources/ReviewKit/RatingImage.swift
  Sources/ReviewKit/RatingPosition.swift
  Sources/ReviewKit/RatingRow.swift
  Sources/ReviewKit/ReviewKit.swift
  Sources/ReviewKit/ReviewManager.swift
Labels: Hacktoberfest-accepted

#26 feat(view): add loading view while fetching app's rating score
  Sources/ReviewKit/ReviewKit.swift
Labels: feature, p1, Hacktoberfest, Hacktoberfest-accepted

#32 Add the Finnish localization
  Sources/ReviewKit/Resources/fi.lproj/Localizable.strings
Labels: feature, Hacktoberfest, Hacktoberfest-accepted
